server:
  port: 8080
  servlet:
    context-path: /address-app/api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SpringBoot
    username: root
    password: system
  application:
    name: address-app